version: '3.8'
services:
    db:
        container_name: postgres
        image: postgres:14.3-alpine
        environment:
            POSTGRES_PASSWORD: Rafi123321.
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_DB: DATABASENAME
        ports:
            - 5432:5432
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}',
                ]

volumes:
    my-db:
